# Generated by Django 5.0.9 on 2024-09-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donation_blood_virus_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='blood_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')], null=True),
        ),
    ]
