# Generated by Django 5.0.9 on 2024-09-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
