# Generated by Django 5.0.9 on 2024-10-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_bloodunit_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodunit',
            options={'ordering': ['deposit_date']},
        ),
    ]
