# Generated by Django 5.0.9 on 2024-10-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_bloodunit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodunit',
            options={},
        ),
    ]
