# Generated by Django 5.0.9 on 2024-09-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_units', models.PositiveIntegerField()),
                ('blood_type', models.PositiveSmallIntegerField(choices=[(1, 'A+'), (2, 'A-'), (3, 'B+'), (4, 'B-'), (5, 'O+'), (6, 'O-'), (7, 'AB+'), (8, 'AB-')])),
                ('patient_status', models.PositiveSmallIntegerField(choices=[(1, 'Immediate'), (2, 'Urgent'), (3, 'Normal')])),
                ('request_status', models.PositiveSmallIntegerField(choices=[(1, 'Accepted'), (2, 'Rejected'), (3, 'Pending')])),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_created', to='hospitals.hospital')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
